INSERT INTO USER_SYSTEM (COD_USER,USERNAME,PASSWORD, VERSION) VALUES (1,'admin','21232f297a57a5a743894a0e4a801fc3', 0);

INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 1);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 2);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 3);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 4);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 5);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 6);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 7);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 8);