INSERT INTO USER_SYSTEM (COD_USER,USERNAME,PASSWORD, VERSION) VALUES (1,'finx','204f27cedb3787209e672a6d6bf1fb04', 0);
INSERT INTO USER_SYSTEM (COD_USER,USERNAME,PASSWORD, VERSION) VALUES (2,'laercio','7047ca2fba4b9e0d53a03ca0ba7bed90', 0);
INSERT INTO USER_SYSTEM (COD_USER,USERNAME,PASSWORD, VERSION) VALUES (3,'diego','078c007bd92ddec308ae2f5115c1775d', 0);
INSERT INTO USER_SYSTEM (COD_USER,USERNAME,PASSWORD, VERSION) VALUES (4,'roberta','229e5b1363be0591e674cd57b3bb8645', 0);
INSERT INTO USER_SYSTEM (COD_USER,USERNAME,PASSWORD, VERSION) VALUES (5,'mabel','c54fdf9dd28d984697251054720c50cf', 0);

INSERT INTO USER_SYSTEM (COD_USER,USERNAME,PASSWORD, VERSION) VALUES (10,'maps','04668875412db9993629099fd66d444d', 0);


INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 1);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 2);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 3);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 4);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 5);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 6);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 7);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (1, 8);


INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (2, 1);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (2, 2);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (2, 3);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (2, 4);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (2, 5);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (2, 6);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (2, 7);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (2, 8);

INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (3, 1);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (3, 2);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (3, 3);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (3, 4);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (3, 5);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (3, 6);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (3, 7);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (3, 8);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (3, 9);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (3, 10);

INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (4, 1);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (4, 2);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (4, 3);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (4, 4);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (4, 5);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (4, 6);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (4, 7);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (4, 8);

INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (5, 1);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (5, 2);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (5, 3);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (5, 4);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (5, 5);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (5, 6);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (5, 7);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (5, 8);

INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (10, 1);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (10, 2);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (10, 3);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (10, 4);
INSERT INTO ASSOC_USER_CREDENTIAL (COD_USER, COD_CREDENTIAL) VALUES (10, 5);
